vmware/python-client-for-vmware-cloud-on-aws

pyVMC.py
=> Added BASH on Windows instructions. Added show-connected-accounts and show-compatible-subnets function

pyVMC.py
Example:
python pyVMC.py new-group cgw pktest5 group-based pkremer-Group1
This will create new group pktest5 and will add existing group pkremer-Group1 as a member.
=> Added ability to create nested groups

pyVMC.py
Extends previous commit by allowing for comma delimited list of groups instead of just a single group
=> Allowed for a comma-delimited set of groups added to cgw

pyVMC.py
=> Converted deprecated refresh_token parameter to api-token - closes #11

pyVMC.py
=> Renamed API parameter from api-token to api_token

README.md, pyVMC.py
=> Added show-csp-groups and show-csp-group-members

requirements.txt
=> Bump requests and urllib versions

pyVMC.py, requirements.txt
add-users-to-csp-group, show-csp-groups,show-csp-group-members,show-csp-group-diff,show-csp-group-users commands
=> Add CSP group management commands

README.md
=> Added new CSP features to doc

pyVMC.py
=> Suppressed verbose output on group create

pyVMC.py
added 2 new functions:
1. creating / uploading prefix filters using PATCH
Added new function to prompt for user input and create prefix filters, which may then be uploaded to customer SDDC.   This is to avoid the use of RAW REST API and postman, making it easier / faster to customize networking in the SDDC.  Function includes the ability to abort / abandon in the event the user makes a mistake with their filter.  ... future capability will include attaching filters to BGP neighbors; this functionality is not yet included.
2. removing prefix filters
Added a new function to remove prefix filters from the SDDC.
Testing was performed using a temporary SDDC deployed for the purpose of testing this specific functionality.  Results were compared with similar functions using POSTman to ensure …
=> feature: add and remove prefix lists

README.md
=> Add link to patrickkremer.com PyVMC blog posts to README

pyVMC.py
=> fix: resolves display issues related to find-csp-user-by-service-role

pyVMC.py
Convert find-csp-user-by-service-role to use PrettyTable
Removed unnecessary debug code from addUsersToCSPGroup
=> Fixes to find-csp-user-by-service-role and addUsersToCSPGroup

pyVMC.py
removed unnecessary, commented lines used for troubleshooting from new-t0-prefix-list and remove-t0-prefix-list
=> removed unnecessary, commented lines used for troubleshooting

pyVMC.py
change menu selection for new-t0-prefix-list to be more user friendly and readable.  Tested against test SDDC to ensure functionality.
=> feature: better menu for new-t0-prefix-list

pyVMC.py
Signed-off-by: Michael Armstrong <michael@m80arm.co.uk>
=> Spelling Mistake

README.md
=> Updated README with latest commands

pyVMC.py
=> Usability update: Updated show-t0-routes to display with PrettyTables

pyVMC.py
Table now sorts by Network and Route Type
=> Bug: Updated sort for show-t0-route table

config.ini.example, pyVMC.py, requirements.txt
=> Addition for VTC and TKG

pyVMC.py, pyvmc_csp.py, pyvmc_nsx.py
=> Renamed refactored functions

pyVMC.py, pyvmc_csp.py, pyvmc_nsx.py, pyvmc_vmc.py
=> More refactoring work.  NSX AF work beginning

pyVMC.py, pyvmc_nsx.py
=> Reorganized pyVMC

pyVMC.py, pyvmc_nsx.py
=> Refactored VPN functions

pyVMC.py, pyvmc_nsx.py
refactor of:
- attach-t0-prefix-list
- detach-t0-prefix-lists
- new-t0-prefix-list
- remove-t0-prefix-list
- show-t0-bgp-neighbors
- show-t0-bgp-routes
- show-t0-prefix-lists
- show-t0-routes: show
=> updated functions for show routes and prefix lists refactor

.gitignore, pyVMC.py, pyvmc_nsx.py
Refactored AWS Account and VPC Functions
Refactored SDDC Functions
=> Refactored more functions

pyVMC.py, pyvmc_nsx.py
refactoring of networking and routing functions, addition of show-t0-static-routes
=> refactoring of networking and routing functions

README.md, config.ini.example, pyVMC.py, pyvmc_csp.py, pyvmc_vcdr.py
New commands supported for VCDR
Updated logic for VCDR Orchestrator discovery
Updated README file, including section for "Known Issues"
=> Updated support for VMware Cloud DR

pyVMC.py, pyvmc_csp.py, pyvmc_nsx.py, pyvmc_vmc.py
Feature: Added new error handling to recently refactored NSX and CSP functions
=> Feature: refactored NAT functions.

pyVMC.py
=> bug fix: fixed retrieval of VCDR orchestrator URL to use only config.ini

pyVMC.py, pyvmc_nsx.py
=> Feature: refactored DFW and Public IP addressing

pyVMC.py, pyvmc_nsx.py
=> BUG: updated returned payload for attach and detach prefix filter functions, eliminated duplicate function for detach prefix filter.

pyVMC.py
=> bug: fixed search logic in search-nsx, missing argument in new-segment

pyVMC.py, pyvmc_nsx.py
Feature: Refactored inventory groups
=> Bug: Fixed Inventory Group display bug

pyVMC.py, pyvmc_nsx.py, requirements.txt
=> Added functionality to create an IDS profile

README.md, pyVMC.py, pyvmc_csp.py
Fixed show-csp-groups error handling. added argument so you can do string search
=> Fixed show-csp-groups error handling

pyVMC.py, pyvmc_csp.py, pyvmc_vmc.py
Fixed f-strings that Chris asked me to, also added a main() function to make debugging cleaner and the stack present a smidge cleaner. Also found a bug in show-compatible-subnets in the error handling. Was bombing out if you put in a bad obj id.
=> Fixed f-strings, main,&bug:show-compatible-subnets

pyVMC.py
basic framework for argparse introduced; this will allow the use of argparse for all commands in the tool, enabling true CLI / scripting capability.  Refactor work to proceed next.
=> introduction of argparse to MAIN to begin refactor effort

pyVMC.py, pyvmc_nsx.py, pyvmc_vmc.py
Most of the work in this batch is implementing sddc commands in the new arg parse structure.
Most are in pyvmc.py
Changes in the functional modules are to implement receipt of the param bundle from arg parse and to regularize the error handling.
Also updated all exit/sys.exit with an error code, so we can use shell error codes for our test harness.
=> sddc commands with exit code cleanup

pyVMC.py, pyvmc_csp.py
updated commands for argparse:
show-routes
add-users-to-csp-group
find-csp-user-by-service-role
show-csp-group-diff
show-csp-group-members
show-csp-groups
search-csp-org-users
show-org-users
=> updated commands for CSP and show-routes to leverage argparse

pyVMC.py
restructured all commands to use sub-commands.  Also reordered them to follow UI in CSP
=> restructured all commands to use sub-commands.

README.md, docs/1-csp_help.txt, docs/10-dfw_help.txt, docs/11-nsxaf_help.txt, docs/12-inventory_help.txt, docs/13-system_help.txt, docs/14-search-nsx_help.txt, docs/15-vcdr_help.txt, docs/2-sddc_help.txt, docs/3-tkg_help.txt, docs/4-segment_help.txt, docs/5-vpn_help.txt, docs/6-nat_help.txt, docs/7-t1_help.txt, docs/8-vtc_help.txt, docs/9-gwfw_help.txt
updated README and added docs folder for help files
=> Updated README and docs folder

README.md, docs/release-notes.md
=> Moved release notes to separate file in DOCS to track and keep history.

docs/2-sddc_help.txt, pyVMC.py, pyvmc_nsx.py, pyvmc_vmc.py
create/delete sddc,watch/cancel task,doc update. will pull out task object later.
=> create/delete sddc,watch/cancel task,doc update

pyVMC.py, pyvmc_nsx.py
Enhancement:
The following commands have been updated to use argparse:
./pyVMC.py gwfw new-cgw-rule
./pyVMC.py gwfw new-mgw-rule
./pyVMC.py gwfw remove-cgw-rule
./pyVMC.py gwfw remove-mgw-rule
./pyVMC.py gwfw show-cgw-rule
./pyVMC.py gwfw show-mgw-rule
=> Enhancement: Refactored GW firewall rule commands to use argparse.

README.md
Closes #122
Signed-off-by: Patrick Kremer <kremerpt@amazon.com>
=> docs: Update README with required role permissions for token

pyVMC.py, pyvmc_vmc.py
Fixing issue #121 which correctly reports a bad or mangled SDDC ID in the config.ini file.
=> fixed issue 121

pyVMC.py, pyvmc_nsx.py
Enhancement: updated IDS commands to use argparse, corrected some API calls
=> Enhancement: IDS commands

pyVMC.py, pyvmc_csp.py, pyvmc_nsx.py, pyvmc_vcdr.py, pyvmc_vmc.py
Enhancement: refactored new-service and show-service for argparse
Enhancement: Added global NSX API handler for pyvmc_nsx
=> Enhancement: refactored new-service and show-service for argparse

pyVMC.py, pyvmc_nsx.py
=> Enhancement: updated new-inv-group to use argparse and new modules.

pyVMC.py, pyvmc_nsx.py
=> Adding new-ike-profile command

pyVMC.py, pyvmc_nsx.py
=> Refactor of more VPN commands

pyVMC.py, pyvmc_nsx.py, pyvmc_vmc.py
Refactored NAT rule commands to leverage argparse.
=> Enhancement: refactor of NAT commands

README.md, docs/16-flexcompute_help.txt, pyVMC.py
- Adding documentation for Cloud Flex Compute
- Also bug fix for https://github.com/vmware/python-client-for-vmware-cloud-on-aws/issues/140 
Signed-off-by: Mandar Bapat [bapatm@vmware.com](mailto:bapatm@vmware.com)
=> Upading documents with Cloud Flex Compute and a small bug fix.

pyVMC.py
Closes #142
Signed-off-by: Patrick Kremer <kremerpt@amazon.com>
=> bug: Replaced staging URL with prod

pyVMC.py
Closes #144
Signed-off-by: Patrick Kremer <kremerpt@amazon.com>
=> Add System Owned column to inventory show-services

pyVMC.py, pyvmc_vmc.py
1. Things that need to be fixed: Create Group will not work with oAuth
2. I have not tested create-sddc-group with pulling the SDDC from the command line. it should work.
3. You'll likely hate the way I print out the task while its executing
4. You will likely need to create an "add member" and "delete member" of a sddc-group
5. Creating an SDDC group takes about 4 minutes for me
6. Delete group does not work yet
7. I have not been able to get create to work with more than 1 node due to quota issues
Here are my args for launch.json for testing:
```
//            "args" : ["sddc", "create", "NewRothSDDC", "56a0415f-1eda-3ea0-96a6-bfba86002ca4", "US_WEST_2", "2" ,"i3.metal", "subnet-86dd90cd", "medium"],
//            "args" : ["sddc", "delete", "89f63521-4d08-473f-b9ec-94286d121693"],
// …
```
=> deployment groups and create sddc w. size

pyVMC.py, pyvmc_vmc.py
also reframed the arguments as optional instead of positional, but enforced through required = True
=> Added argument for SDDC create to enforce inclusion of SDDC mgt subnet

pyvmc_fxns.py
=> Bug: Validates T1 name before deletion.

pyVMC.py, pyvmc_fxns.py
=> Bug: SDDC create will now take either the AWS account number or GUID.
